"""
04_run_lizard.py

Misura, per ogni PR del subset:
  1. Complessita' Ciclomatica (CCN) tramite Lizard, sui file/funzioni
     modificati dalla PR.
  2. Green Smell Density: Si costruisce
     come rapporto tra "unita' di codice (funzioni) che violano soglie
     associate a code smell ad alto consumo energetico" e il totale delle
     funzioni analizzate. Le soglie sono parametri di configurazione (vedi
     configs/green_smells_thresholds.json).

Installazione:
    pip install lizard --break-system-packages

Uso:
    python lizard --csv <file_o_cartella>   # CLI
    oppure, come qui, tramite l'API python: import lizard; lizard.analyze_file(...)

OTTIMIZZAZIONI (rispetto a una versione precedente piu' semplice):
  - PRE-FILTRO DEI FILE: si passano a Lizard solo i file di cui riconosce il
    linguaggio (via lizard.get_reader_for). Circa meta' dei file recuperati
    dalle PR non e' codice sorgente (.md, .json, .png, .txt, lock file...):
    passarli comunque a Lizard significava aprirli e tentarne il parsing per
    poi scartarli, raddoppiando di fatto il lavoro inutilmente.
  - CLASSIFICAZIONE VETTORIZZATA: le soglie dei green smell sono applicate
    con operazioni vettoriali su colonne invece che con apply(axis=1) riga
    per riga, che su oltre centomila funzioni e' molto lento.
  - LOG DI AVANZAMENTO: lo script stampa periodicamente a che punto e',
    cosi' su campioni grandi si distingue "sta lavorando" da "e' bloccato".

Output: results/sustainability/lizard_metrics.csv (una riga per funzione)
        results/sustainability/green_smell_density.csv (una riga per PR)
"""

import lizard
import pandas as pd
import json
import time
from pathlib import Path
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = PROJECT_ROOT / "results"
SUBSET_DIR = RESULTS_DIR / "subset"
SUSTAINABILITY_DIR = RESULTS_DIR / "sustainability"
CONFIGS_DIR = PROJECT_ROOT / "configs"

# Ogni quante PR stampare l'avanzamento
LOG_EVERY = 50

# ---------------------------------------------------------------------------
# ESCLUSIONE DEL CODICE NON SCRITTO DALL'AGENTE
# ---------------------------------------------------------------------------
# Una PR puo' includere file che l'agente non ha scritto: dipendenze copiate
# nel repository (vendoring), codice generato automaticamente da strumenti
# (protobuf, client API, ORM) e artefatti di build (bundle JavaScript
# minificati). Misurarne la complessita' e attribuirla all'agente e' scorretto:
# la metrica descriverebbe la libreria di terzi o il generatore di codice, non
# il lavoro dell'agente.
#
# L'effetto osservato sul campione di 1000 PR e' rilevante e ASIMMETRICO:
# il 38% delle funzioni ricadeva in questa categoria, ma concentrata su due
# soli agenti (circa il 60% delle funzioni di uno, il 24% di un altro, ~0%
# per gli altri tre). Senza il filtro il confronto tra agenti risultava
# invertito rispetto ai dati filtrati.
#
# I path sono "appiattiti" da safe_path() in 02_fetch_files.py (i separatori
# '/' diventano '__'), quindi una cartella "vendor/" compare come "vendor__".
EXCLUDE_PATTERNS = [
    # dipendenze copiate nel repository
    "vendor__", "node_modules__", "third_party__", "thirdparty__", "external__",
    # codice generato automaticamente
    "__proto__", "__generated__", "_pb2", ".pb.", "__gen__",
    "autogenerated", "auto_generated",
    # artefatti di build / bundle
    "public__js__", "dist__", "build__", "__bundle", ".min.",
]


def is_codice_agente(filepath: str) -> bool:
    """
    False se il file e' riconducibile a dipendenze vendorizzate, codice
    generato o artefatti di build (vedi EXCLUDE_PATTERNS): in tal caso non
    e' codice scritto dall'agente e va escluso dalle metriche.
    """
    low = str(filepath).lower()
    return not any(p.lower() in low for p in EXCLUDE_PATTERNS)


def load_thresholds() -> dict:
    with open(CONFIGS_DIR / "green_smells_thresholds.json", encoding="utf-8") as f:
        return json.load(f)


def is_analyzable(filepath: str) -> bool:
    """
    True se Lizard riconosce il linguaggio del file (e quindi ha senso
    analizzarlo). Si usa l'API di Lizard stesso invece di una lista di
    estensioni scritta a mano, cosi' il filtro resta allineato ai linguaggi
    effettivamente supportati dalla versione installata.
    """
    try:
        return lizard.get_reader_for(filepath) is not None
    except Exception:
        # Se l'API non fosse disponibile in questa versione, non si filtra
        # nulla: si torna al comportamento precedente (analizza tutto).
        return True


def analyze_file(filepath: str, pr_id, agent: str) -> list[dict]:
    """Analizza un singolo file con Lizard e ritorna una riga per funzione."""
    rows = []
    try:
        result = lizard.analyze_file(filepath)
    except Exception as e:
        log.warning(f"Lizard fallito su {filepath}: {e}")
        return rows

    for func in result.function_list:
        rows.append({
            "pr_id": pr_id,
            "agent": agent,
            "file": filepath,
            "function_name": func.name,
            "ccn": func.cyclomatic_complexity,
            "nloc": func.nloc,                  # lines of code (no comments/blank)
            "token_count": func.token_count,
            "parameter_count": len(func.parameters),
            "max_nesting_depth": getattr(func, "top_nesting_level", None),
            "long_name": func.long_name,
        })
    return rows


def classify_green_smells(func_row: dict, thresholds: dict) -> list[str]:
    """
    Applica soglie configurabili per etichettare una funzione con uno o piu'
    "green code smell" (proxy di inefficienza/consumo energetico).

    NOTA: nel flusso principale la classificazione avviene in forma
    vettorizzata (vedi main); questa funzione resta disponibile per l'uso
    su una singola funzione, ad esempio in analisi esplorative.
    """
    smells = []
    if func_row["ccn"] > thresholds["high_ccn"]:
        smells.append("high_cyclomatic_complexity")
    if func_row["nloc"] > thresholds["long_method_nloc"]:
        smells.append("long_method")
    if func_row["parameter_count"] > thresholds["too_many_parameters"]:
        smells.append("long_parameter_list")
    if func_row.get("max_nesting_depth") and func_row["max_nesting_depth"] > thresholds["deep_nesting"]:
        smells.append("deep_nesting")
    return smells


def main():
    subset_pr = pd.read_parquet(SUBSET_DIR / "subset_pull_requests.parquet")
    thresholds = load_thresholds()

    n_pr = len(subset_pr)
    log.info(f"PR da analizzare: {n_pr}")

    all_function_rows = []
    n_file_visti = 0
    n_file_analizzati = 0
    n_file_esclusi = 0
    t0 = time.time()

    for i, (_, pr) in enumerate(subset_pr.iterrows(), start=1):
        # Si analizzano i file scaricati da 02_fetch_files.py, versione
        # "after" (post-merge), gia' filtrati ai soli file toccati dalla PR.
        # Questo e' preferibile al repo intero: la metrica e' attribuibile
        # all'agente, non a codice preesistente non toccato dalla PR.
        files_dir = PROJECT_ROOT / "data" / "files" / str(pr["id"]) / "after"
        if not files_dir.exists():
            continue

        source_files = [str(p) for p in files_dir.iterdir() if p.is_file()]
        # I file sono salvati da 02_fetch_files.py con safe_path(), che
        # preserva l'estensione originale in coda (es. "..._a1b2c3d4.py"),
        # quindi Lizard riconosce correttamente il linguaggio.
        n_file_visti += len(source_files)

        # PRE-FILTRO 1: solo i file di cui Lizard riconosce il linguaggio.
        source_files = [f for f in source_files if is_analyzable(f)]

        # PRE-FILTRO 2: esclude il codice NON scritto dall'agente (dipendenze
        # vendorizzate, codice generato, artefatti di build). Vedi la nota su
        # EXCLUDE_PATTERNS: senza questo filtro le metriche di complessita'
        # risultano gravemente distorte e il confronto tra agenti si inverte.
        n_prima_filtro = len(source_files)
        source_files = [f for f in source_files if is_codice_agente(f)]
        n_file_esclusi += n_prima_filtro - len(source_files)

        n_file_analizzati += len(source_files)

        for f in source_files:
            rows = analyze_file(f, pr["id"], pr["agent"])
            all_function_rows.extend(rows)

        if i % LOG_EVERY == 0:
            el = time.time() - t0
            log.info(
                f"  {i}/{n_pr} PR | file analizzati: {n_file_analizzati}"
                f" (esclusi {n_file_esclusi} generati/vendored) | funzioni: {len(all_function_rows)}"
                f" | {el/60:.1f} min"
            )

    log.info(
        f"Scansione completata in {(time.time()-t0)/60:.1f} min. "
        f"File analizzati: {n_file_analizzati} su {n_file_visti} presenti. "
        f"Saltati: {n_file_visti - n_file_analizzati - n_file_esclusi} non "
        f"riconosciuti da Lizard, {n_file_esclusi} esclusi perche' "
        f"generati/vendored/build."
    )

    func_df = pd.DataFrame(all_function_rows)
    SUSTAINABILITY_DIR.mkdir(parents=True, exist_ok=True)
    func_df.to_csv(SUSTAINABILITY_DIR / "lizard_metrics.csv", index=False)

    if func_df.empty:
        log.info("Nessuna funzione analizzata. Controllare i path dei repo checkoutati.")
        return

    # --- Classificazione green smell in forma VETTORIZZATA ---
    # (equivalente a classify_green_smells applicata riga per riga, ma
    # calcolata su colonne intere: su >100k funzioni la differenza di tempo
    # e' sostanziale)
    flag_ccn = func_df["ccn"] > thresholds["high_ccn"]
    flag_nloc = func_df["nloc"] > thresholds["long_method_nloc"]
    flag_par = func_df["parameter_count"] > thresholds["too_many_parameters"]
    nesting = pd.to_numeric(func_df["max_nesting_depth"], errors="coerce")
    flag_nest = nesting.notna() & (nesting > thresholds["deep_nesting"])

    func_df["smell_high_ccn"] = flag_ccn
    func_df["smell_long_method"] = flag_nloc
    func_df["smell_long_parameter_list"] = flag_par
    func_df["smell_deep_nesting"] = flag_nest
    func_df["n_smells"] = (
        flag_ccn.astype(int) + flag_nloc.astype(int)
        + flag_par.astype(int) + flag_nest.astype(int)
    )

    # Riscrive il CSV includendo le colonne degli smell
    func_df.to_csv(SUSTAINABILITY_DIR / "lizard_metrics.csv", index=False)

    # Green Smell Density per PR = funzioni con >=1 smell / funzioni totali
    density = (
        func_df.groupby("pr_id")
        .agg(
            n_functions=("function_name", "count"),
            n_functions_with_smell=("n_smells", lambda x: (x > 0).sum()),
            avg_ccn=("ccn", "mean"),
            max_ccn=("ccn", "max"),
        )
        .reset_index()
    )
    density["green_smell_density"] = density["n_functions_with_smell"] / density["n_functions"]
    density = density.merge(subset_pr[["id", "agent"]], left_on="pr_id", right_on="id", how="left")

    density.to_csv(SUSTAINABILITY_DIR / "green_smell_density.csv", index=False)
    log.info(f"Calcolata densita' di green smell per {len(density)} PR")


if __name__ == "__main__":
    main()